microsoft/folio

- src/fixtures.ts
- src/index.ts
- src/runner.ts
- src/testGenerator.ts
- src/workerRunner.ts
- test/fixture-errors.spec.ts
- test/fixtures.spec.ts
- overriding of non-existent fixture;
- defining a fixture twice;
- worker fixture depending on test fixture;
- dependency cycle.
Drive-by: use registration id instead of location when computing hash.
References #9.
> feat: detect various fixture errors

- package-lock.json
- src/fixtures.ts
- src/runner.ts
- src/runnerSpec.ts
- src/util.ts
- src/workerRunner.ts
- test/hooks.spec.ts
This fixes multiple issues:
- afterEach hooks are now called before fixtures teardown;
- error in a hook does not prevent other hooks from running;
- error in before hooks blocks the test, but not after hooks or fixtures teardown;
- throwing when hook is used outside of a test file.
References #9.
> fix(hooks): call all the hooks before fixtures teardown

- src/fixtures.ts
- src/runner.ts
- src/runnerSpec.ts
- src/runnerTest.ts
- test/fixture-errors.spec.ts
- test/hooks.spec.ts
- Throw for unknown fixture.
- Throw when beforeAll/afterAll depends on a test fixture.
References #9.
> feat(hooks): validate hook fixtures dependencies

- src/fixtures.ts
- src/index.ts
- test/assets/export-1.fixtures.ts
- test/assets/export-2.fixtures.ts
- test/assets/import-fixtures-both.ts
- test/assets/register-parameter.ts
- test/assets/test-data-visible-in-fixture.ts
- test/assets/test-error-visible-in-fixture.ts
- test/fixture-errors.spec.ts
- test/fixtures.spec.ts
- test/hooks.spec.ts
- test/list-mode.spec.ts
- test/override-fixtures.spec.ts
- test/parameters.spec.ts
- test/stdio.spec.ts
- test/test-info-fixture.spec.ts
- test/worker-index.spec.ts
Changes declare+define to just a define with an object,
but forces to use the resulting instance instead of piling up
on previous fixtures. Also, turns all fixtures that start with
`auto` into auto-instantiated fixtures. See tests for examples.
This should not be too bad for typescript fixture definitions,
except for forcing chaining (or intermediate variable) when
defining both worker and test fixtures:
```ts
const fixtures = baseFixtures.defineWorkerFixtures<{ w: string }>({
w: async () => {},
}).defineTestFixtures<{ t: string }>({
t: async () => {},
});
```
This should allow us to avoid any issues with multiple tests
defining their fixtures differently, because we can use separate
Fixtures class instance, returned from `defineFooFixtures` call.
This new instance is not implemented yet.
> feat(fixtures): new fixtures syntax

- src/expect.ts
- src/fixtures.ts
- src/index.ts
- src/runner.ts
- src/runnerSpec.ts
- src/runnerTest.ts
- src/spec.ts
- src/test.ts
- src/testGenerator.ts
- src/util.ts
- src/workerRunner.ts
- src/workerSpec.ts
- src/workerTest.ts
- test/fixture-errors.spec.ts
- test/fixtures.spec.ts
- test/hooks.spec.ts
- test/override-fixtures.spec.ts
- test/parameters.spec.ts
We now attribute each test/suite to a particular `FixturesImpl` instance, which is a new instance after every `defineTestFixtures` call.
Tests are sharded by workers based on the `FixturesImpl` instance and parameter values.
Each worker assumes that it only runs tests from a single `FixturePool`.
Hooks now require a describe block around them, added various error checks.
> feat: implement new fixtures chaining

- src/spec.ts
- test/parameters.spec.ts
It is called when the test does not depend on any parameters through testParametersPathSegment fixture.
> fix(parameters): default parameter fixture should work

- src/fixtures.ts
- src/index.ts
- src/spec.ts
- test/assets/export-1.fixtures.ts
- test/assets/export-2.fixtures.ts
- test/assets/import-fixtures-both.ts
- test/assets/register-parameter.ts
- test/assets/test-data-visible-in-fixture.ts
- test/assets/test-error-visible-in-fixture.ts
- test/fixture-errors.spec.ts
- test/fixtures.spec.ts
- test/hooks.spec.ts
- test/override-fixtures.spec.ts
- test/parameters.spec.ts
- test/stdio.spec.ts
- test/test-info-fixture.spec.ts
- test/worker-index.spec.ts
Turned out to be less convenient.
> Revert "api: switch from runTest(value) to yield value (#59)"

- src/fixtures.ts
- test/parameters.spec.ts
We mistakenly produced many more tests than needed, because each parameter was collected multiple times.
> fix(parameters): do not duplicate parameters when generating tests

- src/fixtures.ts
- src/spec.ts
- test/fixture-errors.spec.ts
- Calling `runTest()` twice.
- Calling `build()` twice.
- Calling `setTestFixture()` after `build()`.
References #9.
> feat: more diagnostic messages

- src/cli.ts
- src/reporter.ts
- src/reporters/base.ts
- src/reporters/json.ts
- src/reporters/multiplexer.ts
- src/runner.ts
- src/util.ts
- test/exit-code.spec.ts
- test/fixture-errors.spec.ts
- test/fixtures.spec.ts
- test/hooks.spec.ts
We used to issue `onError` with a file before `onBegin`, when getting a syntax error or a fixture validation error while
reading one of the test files. Now, we just exit immediately instead.
If importing was successful, we start running the tests and report worker errors through `Reporter.onError()`.
Fixes #2.
> api(reporter, breaking): remove file from onError

- src/runnerSpec.ts
- src/spec.ts
- src/workerSpec.ts
introduce a type for `'default' | 'skip' | 'only'`
> chore: use type for spec argument

- src/fixtures.ts
- src/reporters/base.ts
- src/reporters/json.ts
- src/reporters/junit.ts
- src/runnerSpec.ts
- src/test.ts
- src/util.ts
- src/workerRunner.ts
- src/workerSpec.ts
- test/list-mode.spec.ts
This patch:
- starts serializing all paths as posix-paths to aid json report portability
- saves file location for specs relative to `config.testDir`
- starts storing `line` and `column` for specs explicitly instead of a
`location` string. This reduces report size and simplifies later
processing.
> feat(json): always serialize paths as posix-paths in json report

- src/reporters/json.ts
- test/json-reporter.spec.ts
It will drastically simplify understanding which specs
render total runs as "failing".
> feat(json): export `spec.ok()` in the JSON reporter.

- README.md
- package.json
- src/reporters/base.ts
- src/reporters/dot.ts
- src/test.ts
- src/testGenerator.ts
- src/testModifier.ts
- test/dot-reporter.spec.ts
- test/exit-code.spec.ts
- test/fixtures.ts
- test/junit-reporter.spec.ts
- test/line-reporter.spec.ts
- test/output-path.spec.ts
- test/retry.spec.ts
- test/test-output-dir-fixture.spec.ts
This patch:
- removes `test.flaky` modifier
- merges `expected-flaky` and `unexpected-flaky` test statuses together.
Now all flakes are considered "expected".
Now if a test flakes:
- it doesn't kill build
- flaked test is printed out in the epilogue
> feat: consider all flakes to be "expected"

- src/transform.ts
Seems to be intended to be environment independent, so we should ignore these configs as e.g. react-scripts is also doing.
Fixes #160
Fixes https://github.com/microsoft/playwright-test/issues/207
cc @JoelEinbinder
> fix(babel): ignore local babel config

- src/reporters/list.ts
This change fixes two issues:
a) not using ansi cursor navigation when no TTY is available. This
improves usage especially on bots like GitHub Actions. (was before broken and showed on-going and success/failed text in the same line)
Fixes #122
b) use unicode '✘' character for failed test to be consistent with the
unicode checkmark for passed tests
See here for the changed output regarding b)
Before:
```
✓ foo (2s)
✓ bar (2s)
1) foo bar (1s)
✓ foobar (2s)
```
After:
```
✓ foo (2s)
✓ bar (2s)
✘ 1) foo bar (1s)
✓ foobar (2s)
```
Tested the follow test-cases manually:
- with tty
- with tty and failing test
- without tty
- without tty and failing test
> chore(reporters): enhance list reporter on bots

- src/spec.ts
- src/types.ts
- src/workerRunner.ts
- test/test-output-dir.spec.ts
Output defaults to the alias or alias-<number> (for reused aliases),
includes 'retry<number>' and 'repeat<number>' when needed.
Snapshot defaults to empty, unless `testInfo.snapshotPathSegement'
is assigned to some other value.
> fix: sort out output and snapshot paths

- README.md
- src/cli.ts
- src/dispatcher.ts
- src/ipc.ts
- src/loader.ts
- src/runner.ts
- src/spec.ts
- src/types.ts
- src/workerRunner.ts
- test/config.ts
- test/global-setup.spec.ts
- Also allow multiple `globalSetup`/`globalTeardown` calls.
- Throw when `globalSetup`/`globalTeardown` is called outside of config file.
> feat(globalSetup): run globalSetup before requiring any test files

- src/dispatcher.ts
- src/index.ts
- src/loader.ts
- src/runner.ts
- src/spec.ts
- src/test.ts
- src/types.ts
- src/workerRunner.ts
- test/env.spec.ts
- test/options.spec.ts
- test/test-extend.spec.ts
- test/test-info.spec.ts
- test/test-output-dir.spec.ts
- test/types-2.spec.ts
- test/types.spec.ts
These two are used for adding an environment to an existing test type.
An example of adding `newValue` to test arguments:
```ts
import { test as base } from './my.config';
const test = base.extend({
beforeEach(args, testInfo) {
const newValue = initValue(args);
return { newValue };
}
});
test('my test', ({ newValue }) => {
});
```
Under the hood:
- test types now form a hierarchy;
- `runWith` call affects all test types from the subtree;
- worker initializes a list of environments instead of a single one.
> feat: support test.extend and test.declare

- src/reporters/junit.ts
- test/junit-reporter.spec.ts
For the nicer readable output.
In the future, we can also try to use CDATA sections for minimal
escaping, probably controlled by an option.
References https://github.com/microsoft/playwright-test/issues/224.
> feat(junit): escape less characters in result xml

- README.md
- src/types.ts
- src/workerRunner.ts
- test/access-data.spec.ts
- test/env-errors.spec.ts
- test/env.spec.ts
- test/hooks.spec.ts
- test/options.spec.ts
- test/retry.spec.ts
- test/stdio.spec.ts
- test/test-extend.spec.ts
- test/test-info.spec.ts
- test/test-output-dir.spec.ts
- test/timeout.spec.ts
- test/types-2.spec.ts
- test/types.spec.ts
- `beforeAll` -> `setupWorker`;
- `afterAll` -> `teardownWorker`;
- `beforeEach` -> `setupTest`;
- `afterEach` -> `teardownTest`;
- `optionsType` -> `workerOptionsType`.
> feat: rename environment methods

- src/index.ts
- src/loader.ts
- src/runner.ts
- src/spec.ts
- src/workerRunner.ts
- test/env.spec.ts
When two test types only differ in the last few
environments, and none of them has `beforeAll` or `afterAll`,
we can reuse the worker. In this case, the worker won't have
to run new `beforeAll`/`afterAll` methods, and will update
the list of envs to run `beforeEach`/`afterEach` for the next test.
> feat: reuse worker process between test types

- src/cli.ts
`process.exit()` may not flush stdio, which in turn can lead to the loss of output.
See https://github.com/nodejs/node/issues/6456.
This issue manifests with `max-failures should work` test being flaky,
where we examine large output and it is sometimes truncated.
> fix(stdio): drain stdio before process.exit

- package.json
- src/index.ts
- src/runner.ts
- src/test.ts
- src/testType.ts
- src/types.ts
- src/workerRunner.ts
- test/options.spec.ts
- test/types.spec.ts
Achieved by replacing `optionsType()` and `testOptionsType()` with `hasBeforeAllOptions()`.
> feat: allow useOptions for worker-level options

- package.json
- src/transform.ts
bump babel because why not, and set `loose: false` because it appears slightly safer than `loose: true`.
> chore(babel): bump babel, loose false

- src/transform.ts
setPublicClassFields: true simplifies how babel transforms class properties.
Without it, babel imports a top level function to define the properties.
This isn't in scope for playwright evaluates, which causes them to throw errors.﻿
I also removed the private variables plugin for the same reason.
> fix(babel): setPublicClassFields: true and remove private vars

- src/cli.ts
- src/ipc.ts
- src/loader.ts
- test/config.spec.ts
When `--config` points to a directory, we either find a config there or run with an empty config.
> feat: allow running without config

- src/cli.ts
- src/dispatcher.ts
- src/ipc.ts
- src/loader.ts
- src/reporters/json.ts
- src/test.ts
- src/types.ts
- src/workerRunner.ts
- test/access-data.spec.ts
- test/json-reporter.spec.ts
- test/types-2.spec.ts
Also remove `testInfo.data`, use `testInfo.annotations` when needed.
> feat: allow specifiyng project metadata that is reported in json

- src/cli.ts
- src/loader.ts
- src/runner.ts
- src/types.ts
- src/util.ts
- test/test-ignore.spec.ts
This changes from relative path match to absolute path match,
to support quite common `npx folio test/foo.spec`, where
test root directory is `test`.
Also treat args as regular expressions.
Fixes #275.
> fix(testmatch): match absolute path, treat args as regex

- src/fixtures.ts
- test/fixtures.spec.ts
- test/folio-test.ts
Complex array and object desctructuring should work now.
```js
test('works', ({ foo: [bar, baz: {x, y} ] }) => {
bar;
x;
y;
});
```
Fixes #162.
> feat(fixtures): support more destructuring patterns

- src/cli.ts
- src/runner.ts
- src/types.ts
This way we get suggestions for built-in ones.
Drive-by: improve wording for CLI options.
> fix: change the format for custom reporter

- README.md
- src/fixtures.ts
- src/golden.ts
- src/reporter.ts
- src/reporters/base.ts
- src/runner.ts
- src/test.ts
- test/config.spec.ts
- test/fixtures.spec.ts
- test/golden.spec.ts
- test/match-grep.spec.ts
- Sync fixture functions actually work now.
- Test title grep includes project name.
- `--update-snapshots` does not fail when updating missing snapshot.
- `--project` performs case-insensitive comparison.
- README has more empty lines and file names in all snippets.
> fix: misc fixes after dogfooding

- src/reporters/base.ts
- test/base-reporter.spec.ts
The second test case was failing before and resulted in `rror: ` instead of `Error: `.
> fix(reporters): print errors without message correctly

- README.md
- src/loader.ts
- src/project.ts
- src/reporters/json.ts
- src/types.ts
- src/workerRunner.ts
- test/golden.spec.ts
- test/test-output-dir.spec.ts
Instead of `__snapshots__/path/to/file/test-name/suffix/file.png`
we now have `path/to/file.spec.ts-snapshots/test-name-suffix-file.png`.
> feat(snapshots): change snapshots location

- README.md
- src/loader.ts
- src/runner.ts
- test/global-setup.spec.ts
Drive-by: support `export default` there as well.
> feat(global setup): allow returning teardown

- package.json
- src/golden.ts
- test/base-reporter.spec.ts
This way we do not bring two copies of pngs and source-map.
> chore: update deps to match "deps of deps" versions
