microsoft/folio

README.md, src/cli.ts, src/runner.ts, test/fixtures.ts, test/parameters.spec.ts, test/register-parameter.spec.ts
=> feat(params): allow generating tests from command line

src/runner.ts, src/util.ts, src/workerRunner.ts, test/exit-code.spec.ts
raceAgainstTimeout actually accepts the deadline, not timeout.
=> fix(global timeout): pass deadline instead of timeout

README.md, src/cli.ts, src/runner.ts, test/fixtures.ts, test/parameters.spec.ts, test/register-parameter.spec.ts
Fixes https://github.com/microsoft/playwright-test-runner/issues/25
=> fix: allow arbitrary order of params

src/fixtures.ts, src/index.ts, test/parameters.spec.ts
Fixes https://github.com/microsoft/playwright-test-runner/issues/30
=> fix(auto): account for parameters that auto fixtures depend on

README.md, src/cli.ts, src/config.ts, src/dispatcher.ts, src/runner.ts, test/fixtures.ts
=> chore: rename --jobs to --workers, leave -j

.eslintignore, src/worker.ts, test/fixtures.spec.ts
We used to only teardown the worker fixtures.
Fixes #40.
=> fix(fixtures): teardown test fixtures upon worker shutdown

src/reporters/base.ts, test/base-reporter.spec.ts
=> fix(formatter): tolerate long test titles

src/index.ts, src/spec.ts, test/fixtures.ts, test/test-spec.spec.ts
Fixes https://github.com/microsoft/playwright-test-runner/issues/43
=> feat(spec): support test() notation

src/dispatcher.ts, src/fixtures.ts, src/ipc.ts, src/runnerTest.ts, src/testGenerator.ts, src/workerRunner.ts, test/output-path.spec.ts, test/repeat-each.spec.ts
Fixes https://github.com/microsoft/playwright-test-runner/issues/38
=> fix(repeat): disambiguate repeat-each output paths

package.json, src/cli.ts, src/ipc.ts, src/reporter.ts, src/reporters/base.ts, src/reporters/dot.ts, src/reporters/json.ts, src/reporters/junit.ts, src/reporters/line.ts, src/reporters/multiplexer.ts, src/runner.ts, src/test.ts, src/util.ts, test/dot-reporter.spec.ts, test/fixtures.ts, test/junit-reporter.spec.ts
Fixes https://github.com/microsoft/playwright-test/issues/139
=> feat(junit): add a junit reporter

src/fixtures.ts, test/override-fixtures.spec.ts
=> fix: union with overrides to work

src/fixtures.ts, src/index.ts, src/spec.ts, test/assets/export-1.fixtures.ts, test/assets/export-2.fixtures.ts, test/assets/import-fixtures-both.ts, test/assets/register-parameter.ts, test/assets/test-data-visible-in-fixture.ts, test/assets/test-error-visible-in-fixture.ts, test/fixture-errors.spec.ts, test/fixtures.spec.ts, test/hooks.spec.ts, test/override-fixtures.spec.ts, test/parameters.spec.ts, test/stdio.spec.ts, test/test-info-fixture.spec.ts, test/worker-index.spec.ts
```ts
const newFixtures = oldFixtures.defineWorkerFixtures({
foo: async function*({ bar }) {
await setup;
yield value;
await teardown;
}
});
```
=> api: switch from runTest(value) to yield value

src/fixtures.ts, test/fixture-errors.spec.ts, test/fixtures.spec.ts
The following produces `foo === 2` in tests.
```ts
builder.setTestFixture('foo', async ({}, run) => run(1));
builder.overrideTestFixture('foo', async ({ foo }, run) => run(foo + foo));
```
This only enables "augment fixture result" scenario,
but not the "prepare something before running fixture".
=> feat(fixtures): allow depending on base from override

src/dispatcher.ts
Consider the following scenario: we have two tests that should run in different worker.
Currently, the following race is possible:
1. We create a worker for the first test and run it.
2. We need a worker for the second test, and since first worker is busy, we spawn a new one.
3. While second worker is initializing, the first one finishes and is ready for reuse.
4. We grab the first worker for the second test. However, it does not match the hash, so we spawn the third worker.
Overall, we get three workers instead of two. The solution is to specifically wait for the newly created worker, and leave reusable workers for future tests.
This race was often seen on the bots when running "should work with two different fixture objects".
=> fix: workers creation race

README.md, src/index.ts, src/runnerSpec.ts, src/spec.ts, src/test.ts, src/testGenerator.ts, src/workerRunner.ts, src/workerSpec.ts, test/assets/export-1.fixtures.ts, test/assets/export-2.fixtures.ts, test/assets/import-fixtures-both.ts, test/fixture-errors.spec.ts, test/fixtures.spec.ts
```ts
fixtures.myTestFixture.initTest(fn, options?);
fixtures.myWorkerFixture.initWorker(fn, options?);
fixtures.myParameter.initParameter(description, defaultValue);
```
=> api: support proxy syntax

package.json, src/runnerSpec.ts, src/runnerTest.ts, src/testGenerator.ts, test/parameters.spec.ts
Fixes https://github.com/microsoft/folio/issues/105
=> fix(hooks): respect parameter usage inside hooks

src/reporters/line.ts
Fixes https://github.com/microsoft/folio/issues/115
=> fix(line): respect terminal size in line reporter

src/runner.ts, src/test.ts, src/testGenerator.ts
Fixes https://github.com/microsoft/folio/issues/111
=> fix(generator): don't generate filtered-out tests

src/cli.ts, src/config.ts, src/runner.ts, test/override-timeout.spec.ts
=> fix(timeout): prefer value from the command line

src/cli.ts, test/test-ignore.spec.ts
Fixes https://github.com/microsoft/folio/issues/127, #126
=> fix(ignore): ignore node_modules by default

src/reporters/base.ts
Fixes https://github.com/microsoft/folio/issues/130
=> feat(report): include list of failings tests in the summary

src/workerRunner.ts, test/timeout.spec.ts
Fixes https://github.com/microsoft/folio/issues/134
=> feat(timeout): run test fixture teardown upon timeout

src/reporters/base.ts, src/reporters/line.ts, src/reporters/list.ts, test/list-reporter.spec.ts
=> feat(reporters): use the common test title format

README.md, src/runner.ts, src/spec.ts, src/types.ts, src/util.ts, src/worker.ts, src/workerRunner.ts, test/timeout.spec.ts, tsconfig.json
This function can be used from inside the test or a hook.
Fixes #23.
=> feat(timeout): support test.setTimeout

README.md, src/types.ts, src/workerRunner.ts, test/access-data.spec.ts, test/env-errors.spec.ts, test/env.spec.ts, test/hooks.spec.ts, test/options.spec.ts, test/retry.spec.ts, test/stdio.spec.ts, test/test-extend.spec.ts, test/test-info.spec.ts, test/test-output-dir.spec.ts, test/timeout.spec.ts, test/types-2.spec.ts, test/types.spec.ts
This reverts commit 24cf3ae12df749be6ecfeca8cff72b6a2f47e121.
=> Revert "feat: rename environment methods (#236)"

src/types.ts, src/workerRunner.ts, test/env.spec.ts, test/test-extend.spec.ts, test/types-2.spec.ts
This way type inference works.
=> fix: use the same types in beforeEach and afterEach

src/index.ts, src/loader.ts, src/testType.ts, src/types.ts, src/workerRunner.ts, test/access-data.spec.ts, test/env-errors.spec.ts, test/env.spec.ts, test/hooks.spec.ts, test/options.spec.ts, test/retry.spec.ts, test/stdio.spec.ts, test/test-extend.spec.ts, test/test-info.spec.ts, test/test-output-dir.spec.ts, test/timeout.spec.ts, test/types-2.spec.ts, test/types.spec.ts
Also disallow multiple declares.
=> fix: put defined env in the spot of declared one

src/transform.ts
Otherwise we can pick up dependencies from other packages﻿
=> fix(babel): require.resolve all plugins

test/fixtures.spec.ts, test/types-2.spec.ts
=> test: add tests for sync fixture function

src/reporters/junit.ts, test/junit-reporter.spec.ts
=> fix(junit reporter): add project name to test full title

README.md, src/index.ts, src/types.ts
Export more fixture types, small tweaks in README.
=> chore: misc fixes

src/loader.ts, test/config.spec.ts
Resolved relative to the config file location.
=> feat(config): support relative testDir

src/cli.ts, src/ipc.ts, src/loader.ts, src/runner.ts, src/types.ts, test/config.spec.ts, test/worker-index.spec.ts
This gives us more flexibility.
=> chore: straighten up config overrides and loader

src/cli.ts
=> fix: do not timeout when VSC debugger is attached
